version: '3.8'
services:
  ml:
    build:
      context: ./ml
    ports:
      - '8000:8000'
  backend:
    build: ./backend
    depends_on:
      - ml
    ports:
      - '3000:3000'
  frontend:
    build: ./web
    ports:
      - "5173:5173"
    depends_on:
      - backend