version: '3.8'

services:
  backend:
    build: ./backend
    command: ["python3", "main.py"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  simulator:
    build: ./backend
    command: ["python3", "simulator.py"]
    depends_on:
      - backend
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - backend
